### ISSUE TITLE
Update tts:rubyReserve values 

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#25]
- permitted `tts:rubyReserve` values should be consistent with those of `tts:rubyPosition`
- `auto` is no longer supported by TTML2 (https://github.com/w3c/ttml2/pull/812)

**Comment by palemieux** [comment]
Assuming that only `tts:rubyPosition="outside"` is supported, then only the `none`, `both` and `outside` keywords are required. `both` is required if spacing is to be reserved when multiple `p` are used in a region.

* T = 0
```
-
p1 line 1
-
-
p2 line 1
-
```

* T = 1
```
-
p1 line 1
-
-
p1 line 2
-
-
p2 line 1
-
```

**Comment by nigelmegitt** [comment]
Since `both` is a combination of `before` and `after`, and we have (as far as I know) low evidence of usage requirements, it seems overly restrictive to prohibit specification of those two values. Rather than the solution proposed in the issue I would propose a simpler option just to allow all of `#rubyReserve` as it is now defined in the TTML2 ED.
