### ISSUE TITLE
Exclude support for blur radius in tts:textShadow

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#27]
#textOutline-blurred is _prohibited_.

Suggest similarly not requiring blur radius support in `tts:textShadow`.

**Comment by nigelmegitt** [comment]
I don't understand - [`#textOutline-blurred`](https://www.w3.org/TR/ttml1/#feature-textOutline-blurred) already relates to blur radius, so prohibiting it _means_ that blur radius support is not required in `tts:textOutline`, doesn't it?

Oh, looking at the pull request, maybe this issue is about `tts:textShadow`?

**Comment by nigelmegitt** [comment]
If this is about `tts:textShadow` (which the title suggests!) should we not be adding a `#textShadow-blurred` feature to TTML2?

**Comment by nigelmegitt** [comment]
@palemieux Do you have any more evidence to prohibit blurred text shadows than symmetry with text outline? The aesthetic effect of a hard shadow border is in my opinion much worse than that of a hard outline border, so I expect that restricting text shadow to a hard border will make the whole feature significantly less useful. Where a broad shadow is used to improve readability, it is particularly important to be able to specify a blur radius.

I see [from MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow#Browser_compatibility) that there is good CSS support for blur radius on text shadow in computer-based browsers, and less certain support in mobile browsers.
